### ISSUE TITLE
Deprecation Warning: Use MainViewManager.getViews() instead of DocumentManager.getWorkingSet()

### ISSUE THREAD

**Issue by TuckerWhitehouse** [martypenner/brackets-autosave-files-on-window-blur#4]
Brackets 1.1 throws a deprecation warning about the use of ```DocumentManager.getWorkingSet``` here https://github.com/martypenner/brackets-autosave-files-on-window-blur/blob/master/main.js#L75

**Comment by martypenner** [comment]
Thanks! Looks like you've got things covered. How do you feel about making a pull request?

**Comment by TuckerWhitehouse** [comment]
See #5.
