### ISSUE TITLE
Make feature optional

### ISSUE THREAD

**Issue by Tiagojdferreira** [martypenner/brackets-autosave-files-on-window-blur#6]
It would be great if we could de-activate this feature from time to time. Currently I am working in a project with a rather heavy watch, and this keeps triggering the watch. The only possible work arounds are rather tedious: 
https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually

**Comment by martypenner** [comment]
Sounds like a good case for it. This was brought up in #3 as well. How would you prefer the disable/enable mechanism to work? A menu entry perhaps?

**Comment by Tiagojdferreira** [comment]
Keyboard shortcut and menu

**Comment by martypenner** [comment]
I've added a menu entry under the "Edit" menu, and provided a keyboard shortcut of "Ctrl-Alt-Shift-W" (Cmd on Mac). Let me know if you run into any issues.

**Comment by Tiagojdferreira** [comment]
Seems to work like a charm ;)

**Comment by martypenner** [comment]
Glad to hear it!

**Comment by mar627** [comment]
Hey Marty, is there a way to have this launch in a disabled state via the menu item?

Or even better, just to remember if it was either activated or deactivated between exits and launches. At present its always on at launch, regardless of previous application exit setting.. thanks!

**Comment by martypenner** [comment]
Ah, right. That's kind of important :). I've made an issue for me to investigate in #9.
