### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by pmerrity** [martypenner/brackets-autosave-files-on-window-blur#7]
While debugging Brackets frequent lockups, I noticed that the dev console throws this error, but it's only when this extension is enabled. I don't think it's the cause of Brackets crashing, but wanted to bring it to your attention. Here are screenshots with more details:

![screen shot 2015-10-17 at 11 01 10 am](https://cloud.githubusercontent.com/assets/8050810/10559832/b6bd08a0-74be-11e5-9b43-9e149449593c.png)

![screen shot 2015-10-17 at 11 01 24 am](https://cloud.githubusercontent.com/assets/8050810/10559834/bac664a0-74be-11e5-9fd0-8c53a968d419.png)

**Comment by martypenner** [comment]
Thanks! It's quite possible some recent API change is causing a cascade of issues based on this extension. I assume you're on Brackets 1.5?

**Comment by pmerrity** [comment]
Yes, but it was doing it in 1.4 as well

**Comment by martypenner** [comment]
Cool. I'll look into this within the next few days to see if I can simplify things and solve the issue.

**Comment by martypenner** [comment]
Debugged with only my extension enabled: no deprecation warnings or errors. Traced the problem to [this extension](https://github.com/ucym/Brackets-CSS-Class-Code-hint/issues). Do you mind opening the issue there?
