### ISSUE TITLE
Save As results in saving the original the same way

### ISSUE THREAD

**Issue by tenten71** [martypenner/brackets-autosave-files-on-window-blur#8]
Hey, awesome extension. Co-worker of mine came up with this scenario that messed him up. I consider it to be a small issue.

If you make changes to a file and then decide to Save As, you wind up with 2 copies of the same file (now with different filenames).

The obvious work around is to remember to Save As BEFORE making any changes to your file. Curious if this is fixable for those of us who forget that.

**Comment by martypenner** [comment]
Awesome! Glad it's of use to you :)

Thanks for reporting this. I knew I was missing a case somewhere. After a few hours of digging into the Brackets API, I can find nothing that lets us either **a)** check that a dialog is currently open, or **b)** be notified when a dialog is opened. Either of those would provide a solution. But alas, no such luck. If you happen to come across another way of solving this, don't hesitate to reopen the issue.
